/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LlmPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/ChatView.ts
var import_obsidian2 = require("obsidian");

// src/llmClient.ts
var import_obsidian = require("obsidian");
var DEFAULT_CODEX_API_BASE = "https://chatgpt.com/backend-api/codex/responses";
var CODEX_REFRESH_TOKEN_URL = "https://auth.openai.com/oauth/token";
var CODEX_CLIENT_ID = "app_EMoamEEZ73f0CkXaXp7hrann";
async function callLlmApi(apiUrl, apiKey, model, messages, attachments = [], authMode = "api_key") {
  var _a, _b, _c, _d;
  if (!apiUrl)
    throw new Error("API URL is empty. Please configure it in settings.");
  if (authMode !== "codex_auth" && !apiKey)
    throw new Error("API Key is empty. Please configure it in settings.");
  const isGoogleGemini = apiUrl.includes("generativelanguage.googleapis.com");
  const isAnthropic = apiUrl.includes("api.anthropic.com");
  const isOfficialOpenAI = isOfficialOpenAiApiUrl(apiUrl);
  const isCodexResponses = authMode === "codex_auth" || apiUrl.includes("chatgpt.com/backend-api/codex/responses");
  if (isCodexResponses) {
    const auth = await resolveCodexAuthState();
    let response = await postCodexRequest({
      apiUrl,
      model,
      messages,
      token: auth.accessToken
    });
    if (response.status === 401 && auth.refreshToken) {
      const refreshedToken = await refreshCodexAccessToken(auth.refreshToken, auth.authPath);
      response = await postCodexRequest({
        apiUrl,
        model,
        messages,
        token: refreshedToken
      });
    }
    if (response.status < 200 || response.status >= 300) {
      throw new Error(response.text || `Codex request failed, status ${response.status}`);
    }
    if (typeof response.text === "string" && (response.text.includes("data:") || response.text.includes("event:"))) {
      return extractCodexTextFromSSE(response.text);
    }
    try {
      return extractCodexText(JSON.parse(response.text));
    } catch (_error) {
      throw new Error(response.text || "Invalid non-streaming response format from Codex");
    }
  } else if (isGoogleGemini) {
    let finalUrl = apiUrl.trim().replace(/\/$/, "");
    if (!finalUrl.includes("/models/")) {
      finalUrl += `/v1beta/models/${model}:generateContent?key=${apiKey}`;
    } else if (!finalUrl.includes("?key=")) {
      finalUrl += `?key=${apiKey}`;
    }
    const systemMsg = messages.find((m) => m.role === "system");
    const chatMsgs = messages.filter((m) => m.role !== "system");
    const contents = chatMsgs.map((m, index) => {
      const parts = [{ text: m.content }];
      if (m.role === "user" && index === chatMsgs.length - 1 && attachments.length > 0) {
        attachments.forEach((att) => {
          parts.push({
            inlineData: {
              mimeType: att.mimeType,
              data: att.data
            }
          });
        });
      }
      return {
        role: m.role === "assistant" ? "model" : "user",
        parts
      };
    });
    const payload = {
      contents,
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 4e3
      }
    };
    if (systemMsg) {
      payload.system_instruction = {
        parts: [{ text: systemMsg.content }]
      };
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: finalUrl,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
        throw: true
      });
      if (response.json && response.json.candidates && response.json.candidates.length > 0) {
        const parts = response.json.candidates[0].content.parts;
        return parts.map((p) => p.text).join("");
      } else {
        throw new Error(((_b = (_a = response.json) == null ? void 0 : _a.error) == null ? void 0 : _b.message) || "Invalid response from Google API");
      }
    } catch (e) {
      console.error("Gemini API Error:", e);
      throw new Error(e.message || "Gemini Request Failed");
    }
  } else if (isAnthropic) {
    let finalUrl = apiUrl.trim();
    if (!finalUrl.endsWith("/v1/messages")) {
      finalUrl = finalUrl.replace(/\/$/, "") + "/v1/messages";
    }
    const systemMessages = messages.filter((m) => m.role === "system").map((m) => m.content.trim()).filter(Boolean);
    const chatMessages = buildAnthropicMessages(messages, attachments);
    const payload = {
      model,
      messages: chatMessages,
      max_tokens: 4e3
    };
    if (systemMessages.length > 0) {
      payload.system = systemMessages.join("\n\n");
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: finalUrl,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify(payload),
        throw: true
      });
      if (response.json && Array.isArray(response.json.content)) {
        return response.json.content.filter((part) => part.type === "text").map((part) => part.text).join("");
      } else {
        throw new Error(((_d = (_c = response.json) == null ? void 0 : _c.error) == null ? void 0 : _d.message) || "Invalid response from Anthropic API");
      }
    } catch (e) {
      console.error("Anthropic API Error:", e);
      throw new Error(e.message || "Anthropic Request Failed");
    }
  } else {
    const defaultHeaders = {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    };
    const payload = isOfficialOpenAI ? {
      model,
      messages: buildOpenAiChatMessages(messages, attachments),
      temperature: 0.7
    } : {
      model,
      messages,
      temperature: 0.7
    };
    let finalUrl = apiUrl.trim();
    if (!finalUrl.endsWith("/chat/completions")) {
      finalUrl = finalUrl.replace(/\/$/, "") + "/chat/completions";
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: finalUrl,
        method: "POST",
        headers: defaultHeaders,
        body: JSON.stringify(payload),
        throw: true
      });
      if (response.json && response.json.choices && response.json.choices.length > 0) {
        return response.json.choices[0].message.content;
      } else {
        throw new Error("Invalid response format from API");
      }
    } catch (e) {
      console.error("LLM API Error:", e);
      throw new Error(e.message || "API Request Failed");
    }
  }
}
function buildAnthropicMessages(messages, attachments) {
  const pdfAttachments = attachments.filter((attachment) => attachment.mimeType === "application/pdf");
  const lastUserIndex = findLastUserMessageIndex(messages);
  return messages.filter((message) => message.role !== "system").map((message, index) => {
    const content = [];
    if (message.role === "user" && index === lastUserIndex && pdfAttachments.length > 0) {
      for (const attachment of pdfAttachments) {
        content.push({
          type: "document",
          source: {
            type: "base64",
            media_type: attachment.mimeType,
            data: attachment.data
          }
        });
      }
    }
    content.push({
      type: "text",
      text: message.content
    });
    return {
      role: message.role,
      content
    };
  });
}
function buildOpenAiChatMessages(messages, attachments) {
  const pdfAttachments = attachments.filter((attachment) => attachment.mimeType === "application/pdf");
  const lastUserIndex = findLastUserMessageIndex(messages);
  return messages.map((message, index) => {
    if (message.role !== "user" || index !== lastUserIndex || pdfAttachments.length === 0) {
      return message;
    }
    const content = pdfAttachments.map((attachment) => ({
      type: "file",
      file: {
        filename: attachment.name,
        file_data: `data:${attachment.mimeType};base64,${attachment.data}`
      }
    }));
    content.push({
      type: "text",
      text: message.content
    });
    return {
      role: message.role,
      content
    };
  });
}
function findLastUserMessageIndex(messages) {
  for (let index = messages.length - 1; index >= 0; index--) {
    if (messages[index].role === "user")
      return index;
  }
  return -1;
}
async function postCodexRequest(params) {
  const finalUrl = normalizeCodexApiUrl(params.apiUrl);
  const payload = buildCodexPayload(params.model, params.messages);
  const response = await (0, import_obsidian.requestUrl)({
    url: finalUrl,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${params.token}`
    },
    body: JSON.stringify(payload),
    throw: false
  });
  return {
    status: response.status,
    text: response.text
  };
}
function buildCodexPayload(model, messages) {
  const instructions = messages.filter((message) => message.role === "system").map((message) => message.content.trim()).filter(Boolean).join("\n\n");
  const input = messages.filter((message) => message.role !== "system").map((message) => ({
    type: "message",
    role: message.role,
    content: message.content
  }));
  return {
    model,
    input,
    ...instructions ? { instructions } : {},
    store: false,
    stream: true
  };
}
function extractCodexText(data) {
  if (typeof (data == null ? void 0 : data.output_text) === "string" && data.output_text.trim()) {
    return data.output_text;
  }
  const output = Array.isArray(data == null ? void 0 : data.output) ? data.output : [];
  const parts = [];
  for (const item of output) {
    const content = Array.isArray(item == null ? void 0 : item.content) ? item.content : [];
    for (const part of content) {
      if (((part == null ? void 0 : part.type) === "output_text" || (part == null ? void 0 : part.type) === "text") && typeof (part == null ? void 0 : part.text) === "string") {
        parts.push(part.text);
      }
    }
  }
  if (parts.length > 0) {
    return parts.join("");
  }
  throw new Error("Invalid response format from Codex");
}
function extractCodexTextFromSSE(raw) {
  var _a, _b;
  const lines = raw.split(/\r?\n/);
  const parts = [];
  let completedText = "";
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("data:"))
      continue;
    const payload = trimmed.slice(5).trim();
    if (!payload || payload === "[DONE]")
      continue;
    try {
      const parsed = JSON.parse(payload);
      if (typeof parsed.delta === "string" && parsed.delta) {
        parts.push(parsed.delta);
      }
      if (typeof ((_a = parsed.response) == null ? void 0 : _a.output_text) === "string" && parsed.response.output_text) {
        completedText = parsed.response.output_text;
      }
      if (!completedText) {
        const output = Array.isArray((_b = parsed.response) == null ? void 0 : _b.output) ? parsed.response.output : [];
        for (const item of output) {
          const content = Array.isArray(item == null ? void 0 : item.content) ? item.content : [];
          for (const part of content) {
            if (((part == null ? void 0 : part.type) === "output_text" || (part == null ? void 0 : part.type) === "text") && typeof (part == null ? void 0 : part.text) === "string") {
              completedText += part.text;
            }
          }
        }
      }
    } catch (_error) {
      continue;
    }
  }
  const text = (completedText || parts.join("")).trim();
  if (!text) {
    throw new Error("Invalid streaming response format from Codex");
  }
  return text;
}
function normalizeCodexApiUrl(apiUrl) {
  const trimmed = apiUrl.trim();
  return trimmed || DEFAULT_CODEX_API_BASE;
}
function isOfficialOpenAiApiUrl(apiUrl) {
  return apiUrl.includes("api.openai.com");
}
async function resolveCodexAuthState() {
  var _a, _b, _c, _d;
  const authPath = resolveCodexAuthPath();
  const auth = await loadCodexAuthJson(authPath);
  const accessToken = ((_b = (_a = auth == null ? void 0 : auth.tokens) == null ? void 0 : _a.access_token) == null ? void 0 : _b.trim()) || "";
  const refreshToken = ((_d = (_c = auth == null ? void 0 : auth.tokens) == null ? void 0 : _c.refresh_token) == null ? void 0 : _d.trim()) || "";
  if (accessToken) {
    return { accessToken, refreshToken, authPath };
  }
  if (refreshToken) {
    const refreshedToken = await refreshCodexAccessToken(refreshToken, authPath);
    return { accessToken: refreshedToken, refreshToken, authPath };
  }
  throw new Error("Codex auth token not found. Please run `codex login` and ensure ~/.codex/auth.json is available.");
}
async function testCodexAuthState() {
  var _a, _b, _c, _d;
  const authPath = resolveCodexAuthPath();
  const auth = await loadCodexAuthJson(authPath);
  const accessToken = ((_b = (_a = auth == null ? void 0 : auth.tokens) == null ? void 0 : _a.access_token) == null ? void 0 : _b.trim()) || "";
  const refreshToken = ((_d = (_c = auth == null ? void 0 : auth.tokens) == null ? void 0 : _c.refresh_token) == null ? void 0 : _d.trim()) || "";
  if (accessToken) {
    return {
      authPath,
      tokenSource: "access_token",
      lastRefresh: auth == null ? void 0 : auth.last_refresh
    };
  }
  if (refreshToken) {
    await refreshCodexAccessToken(refreshToken, authPath);
    const refreshed = await loadCodexAuthJson(authPath);
    return {
      authPath,
      tokenSource: "refresh_token",
      lastRefresh: refreshed == null ? void 0 : refreshed.last_refresh
    };
  }
  throw new Error("No Codex token found in ~/.codex/auth.json. Run `codex login` first.");
}
async function testModelConnection(params) {
  const response = await callLlmApi(
    params.apiUrl,
    params.apiKey,
    params.model,
    [
      {
        role: "system",
        content: "You are a connection test. Reply with only: OK"
      },
      {
        role: "user",
        content: "Reply with only: OK"
      }
    ],
    [],
    params.authMode || "api_key"
  );
  return {
    preview: response.trim().slice(0, 120) || "(empty response)"
  };
}
function resolveCodexAuthPath() {
  const codexHome = getProcessEnvValue("CODEX_HOME");
  if (codexHome) {
    return joinPath(codexHome, "auth.json");
  }
  const homeDir = getProcessEnvValue("HOME") || getProcessEnvValue("USERPROFILE") || getOsHomeDir();
  if (!homeDir) {
    throw new Error("Unable to resolve home directory for Codex auth.");
  }
  return joinPath(homeDir, ".codex", "auth.json");
}
async function loadCodexAuthJson(authPath) {
  try {
    const raw = await readUtf8File(authPath);
    if (!raw.trim())
      return null;
    return JSON.parse(raw);
  } catch (_error) {
    return null;
  }
}
async function refreshCodexAccessToken(refreshToken, authPath) {
  var _a, _b;
  const response = await (0, import_obsidian.requestUrl)({
    url: CODEX_REFRESH_TOKEN_URL,
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      client_id: CODEX_CLIENT_ID,
      grant_type: "refresh_token",
      refresh_token: refreshToken
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(response.text || `Codex token refresh failed, status ${response.status}`);
  }
  const nextAccessToken = typeof ((_a = response.json) == null ? void 0 : _a.access_token) === "string" ? response.json.access_token.trim() : "";
  const nextRefreshToken = typeof ((_b = response.json) == null ? void 0 : _b.refresh_token) === "string" ? response.json.refresh_token.trim() : refreshToken;
  if (!nextAccessToken) {
    throw new Error("Codex token refresh returned empty access token");
  }
  const current = await loadCodexAuthJson(authPath);
  await ensureDir(getParentPath(authPath));
  await writeUtf8File(authPath, `${JSON.stringify({
    ...current || {},
    tokens: {
      ...(current == null ? void 0 : current.tokens) || {},
      access_token: nextAccessToken,
      refresh_token: nextRefreshToken
    },
    last_refresh: new Date().toISOString()
  }, null, 2)}
`);
  return nextAccessToken;
}
function getNodeRequire() {
  const globalRequire = globalThis.require;
  return typeof globalRequire === "function" ? globalRequire : null;
}
function getProcessEnvValue(key) {
  var _a, _b;
  const proc = globalThis.process;
  return ((_b = (_a = proc == null ? void 0 : proc.env) == null ? void 0 : _a[key]) == null ? void 0 : _b.trim()) || "";
}
function getOsHomeDir() {
  try {
    const req = getNodeRequire();
    if (!req)
      return "";
    const os = req("os");
    return typeof os.homedir === "function" ? os.homedir().trim() : "";
  } catch (_error) {
    return "";
  }
}
function joinPath(...parts) {
  return parts.filter(Boolean).map((part, index) => index === 0 ? part.replace(/[\\/]+$/, "") : part.replace(/^[\\/]+|[\\/]+$/g, "")).join("/");
}
function getParentPath(filePath) {
  const normalized = filePath.replace(/[\\/]+$/, "");
  const lastSlash = Math.max(normalized.lastIndexOf("/"), normalized.lastIndexOf("\\"));
  return lastSlash >= 0 ? normalized.slice(0, lastSlash) : "";
}
async function readUtf8File(filePath) {
  var _a;
  const req = getNodeRequire();
  if (!req) {
    throw new Error("Node file APIs are unavailable in this environment.");
  }
  const fs = req("fs");
  if (!((_a = fs.promises) == null ? void 0 : _a.readFile)) {
    throw new Error("fs.promises.readFile is unavailable in this environment.");
  }
  return fs.promises.readFile(filePath, "utf-8");
}
async function writeUtf8File(filePath, content) {
  var _a;
  const req = getNodeRequire();
  if (!req) {
    throw new Error("Node file APIs are unavailable in this environment.");
  }
  const fs = req("fs");
  if (!((_a = fs.promises) == null ? void 0 : _a.writeFile)) {
    throw new Error("fs.promises.writeFile is unavailable in this environment.");
  }
  await fs.promises.writeFile(filePath, content, "utf-8");
}
async function ensureDir(dirPath) {
  var _a;
  if (!dirPath)
    return;
  const req = getNodeRequire();
  if (!req) {
    throw new Error("Node file APIs are unavailable in this environment.");
  }
  const fs = req("fs");
  if (!((_a = fs.promises) == null ? void 0 : _a.mkdir)) {
    throw new Error("fs.promises.mkdir is unavailable in this environment.");
  }
  await fs.promises.mkdir(dirPath, { recursive: true });
}

// src/ChatView.ts
var CHAT_VIEW_TYPE = "llm-chat-view";
var ChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.attachedFiles = [];
    this.typingBubble = null;
    this.currentHistoryPath = null;
    this.activeSessionIndex = null;
    this.historyCache = /* @__PURE__ */ new Map();
    this.floatingMenuEl = null;
    this.maxPdfPages = 100;
    this.plugin = plugin;
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "LLM Assistant";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("llm-chat-wrapper");
    const headerContainer = container.createDiv({ cls: "llm-header" });
    headerContainer.createEl("h3", { text: "LLM Assistant", cls: "llm-header-title" });
    const headerButtons = headerContainer.createDiv({ cls: "llm-header-btns" });
    const addBtn = headerButtons.createEl("button", { text: "New", cls: "llm-header-btn", title: "Start new conversation" });
    addBtn.addEventListener("click", () => this.createNewSession());
    this.historyBtn = headerButtons.createEl("button", { text: "History", cls: "llm-header-btn llm-history-trigger", title: "View past conversations" });
    this.historyBtn.addEventListener("click", () => this.showHistoryExplorer());
    this.chatContainer = container.createDiv({ cls: "chat-history" });
    this.renderWelcomeScreen();
    this.attachmentsDiv = container.createDiv({ cls: "llm-attachments" });
    const suggestionsContainer = container.createDiv({ cls: "llm-shortcuts" });
    const shortcuts = (this.plugin.settings.shortcuts || []).filter((shortcut) => {
      var _a;
      return (_a = shortcut.prompt) == null ? void 0 : _a.trim();
    });
    shortcuts.forEach((s) => {
      var _a;
      const btn = suggestionsContainer.createEl("button", { text: ((_a = s.label) == null ? void 0 : _a.trim()) || "Prompt", cls: "llm-shortcut-btn" });
      btn.addEventListener("click", async () => {
        if (this.sendButton && this.sendButton.disabled)
          return;
        this.textarea.value = "";
        await this.handleSend(s.prompt, this.plugin.settings.model);
      });
    });
    const inputContainer = container.createDiv({ cls: "chat-input-container" });
    this.textarea = inputContainer.createEl("textarea", {
      cls: "chat-input",
      attr: { placeholder: "Ask anything..." }
    });
    this.textarea.addEventListener("input", () => {
      this.textarea.style.height = "auto";
      this.textarea.style.height = this.textarea.scrollHeight + "px";
    });
    const controlsDiv = inputContainer.createDiv({ cls: "chat-controls" });
    const leftControls = controlsDiv.createDiv({ cls: "chat-controls-left" });
    const rightControls = controlsDiv.createDiv({ cls: "chat-controls-right" });
    const attachButton = leftControls.createEl("button", { cls: "llm-minimal-btn", title: "Attach file", attr: { "aria-label": "Attach file" } });
    attachButton.addEventListener("click", () => {
      var _a;
      const activeFile = this.app.workspace.getActiveFile();
      let autoAttached = false;
      if (activeFile && activeFile.extension === "md") {
        const cache = this.app.metadataCache.getFileCache(activeFile);
        const source = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.source;
        if (source && typeof source === "string") {
          const cleanPath = source.replace(/\[\[|\]\]/g, "").split("|")[0].trim();
          const sourceFile = this.app.metadataCache.getFirstLinkpathDest(cleanPath, activeFile.path);
          if (sourceFile && !this.attachedFiles.find((f) => f.path === sourceFile.path)) {
            this.attachedFiles.push(sourceFile);
            this.renderAttachments();
            new import_obsidian2.Notice(`Added source: ${sourceFile.name}`);
            autoAttached = true;
          }
        }
      } else if (activeFile && activeFile.extension === "pdf") {
        if (!this.attachedFiles.find((f) => f.path === activeFile.path)) {
          this.attachedFiles.push(activeFile);
          this.renderAttachments();
          new import_obsidian2.Notice(`Added current PDF: ${activeFile.name}`);
          autoAttached = true;
        }
      }
      if (!autoAttached) {
        new FileSuggestModal(this.app, (file) => {
          if (!this.attachedFiles.find((f) => f.path === file.path)) {
            this.attachedFiles.push(file);
            this.renderAttachments();
          }
        }).open();
      }
    });
    const modelPill = leftControls.createDiv({ cls: "llm-model-pill" });
    const modelSelectWrap = modelPill.createDiv({ cls: "llm-model-select-wrap" });
    const modelSelect = modelSelectWrap.createEl("select", { cls: "llm-minimal-dropdown", attr: { "aria-label": "Select model" } });
    const models = this.plugin.settings.models || [];
    for (const m of models) {
      modelSelect.createEl("option", { value: m.name, text: m.name });
    }
    modelSelect.value = this.plugin.settings.model;
    modelSelect.addEventListener("change", async () => {
      this.plugin.settings.model = modelSelect.value;
      await this.plugin.saveSettings();
    });
    this.sendButton = rightControls.createEl("button", { text: "\u2794", cls: "llm-rounded-send", title: "Send message" });
    this.sendButton.addEventListener("click", async () => {
      const text = this.textarea.value.trim();
      if (!text)
        return;
      this.textarea.value = "";
      this.textarea.style.height = "auto";
      await this.handleSend(text, modelSelect.value);
    });
    this.textarea.addEventListener("keydown", async (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        if (e.isComposing)
          return;
        e.preventDefault();
        const text = this.textarea.value.trim();
        if (!text)
          return;
        this.textarea.value = "";
        this.textarea.style.height = "auto";
        await this.handleSend(text, modelSelect.value);
      }
    });
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.switchHistory()));
    this.setupSelectionMenu();
    this.loadHistoryFromFile().then(() => {
      const initialFile = this.app.workspace.getActiveFile();
      if (initialFile) {
        this.currentHistoryPath = initialFile.path;
        this.loadActiveSession(initialFile);
      }
    });
  }
  async loadHistoryFromFile() {
    try {
      const dataPath = `${this.plugin.manifest.dir}/llm-history.json`;
      if (await this.app.vault.adapter.exists(dataPath)) {
        this.historyCache = new Map(Object.entries(JSON.parse(await this.app.vault.adapter.read(dataPath))));
      }
    } catch (e) {
    }
  }
  async saveHistoryToFile() {
    try {
      const dataPath = `${this.plugin.manifest.dir}/llm-history.json`;
      await this.app.vault.adapter.write(dataPath, JSON.stringify(Object.fromEntries(this.historyCache), null, 2));
    } catch (e) {
    }
  }
  loadActiveSession(file) {
    const sessions = this.historyCache.get(file.path);
    if (sessions && sessions.length > 0) {
      this.activeSessionIndex = sessions.length - 1;
      const last = sessions[this.activeSessionIndex];
      this.messages = [...last.messages];
      this.attachedFiles = last.attached.map((p) => this.app.vault.getAbstractFileByPath(p)).filter((f) => f instanceof import_obsidian2.TFile);
    } else {
      this.messages = [];
      this.attachedFiles = [];
      this.activeSessionIndex = null;
    }
    if (file.extension === "pdf" && !this.attachedFiles.find((f) => f.path === file.path)) {
      this.attachedFiles.push(file);
      if (this.activeSessionIndex === null) {
        this.activeSessionIndex = 0;
        this.historyCache.set(file.path, [{ timestamp: Date.now(), messages: [], attached: [file.path] }]);
      }
    }
    this.renderHistory();
    this.renderAttachments();
  }
  createNewSession() {
    if (!this.currentHistoryPath)
      return;
    const current = this.historyCache.get(this.currentHistoryPath) || [];
    if (this.activeSessionIndex !== null && current[this.activeSessionIndex]) {
      current[this.activeSessionIndex].messages = [...this.messages];
      current[this.activeSessionIndex].attached = this.attachedFiles.map((f) => f.path);
    }
    current.push({ timestamp: Date.now(), messages: [], attached: [] });
    this.historyCache.set(this.currentHistoryPath, current);
    this.activeSessionIndex = current.length - 1;
    this.messages = [];
    this.attachedFiles = [];
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile && activeFile.extension === "pdf") {
      this.attachedFiles.push(activeFile);
      current[this.activeSessionIndex].attached = [activeFile.path];
    }
    this.renderHistory();
    this.renderAttachments();
    this.saveHistoryToFile();
    new import_obsidian2.Notice("Started new conversation");
  }
  setupSelectionMenu() {
    this.registerDomEvent(this.contentEl, "mouseup", () => {
      setTimeout(() => {
        const selection = window.getSelection();
        const text = selection == null ? void 0 : selection.toString().trim();
        if (this.floatingMenuEl) {
          this.floatingMenuEl.remove();
          this.floatingMenuEl = null;
        }
        if (!text || text.length < 3)
          return;
        const range = selection == null ? void 0 : selection.getRangeAt(0);
        const rect = range == null ? void 0 : range.getBoundingClientRect();
        if (!rect)
          return;
        this.floatingMenuEl = document.body.createDiv({ cls: "llm-floating-menu" });
        this.floatingMenuEl.style.left = `${rect.left + rect.width / 2 - 60}px`;
        this.floatingMenuEl.style.top = `${rect.top - 50}px`;
        const addBtn = (t, cb) => {
          const b = this.floatingMenuEl.createEl("button", { cls: "llm-floating-btn", text: t });
          b.addEventListener("mousedown", (ev) => {
            var _a;
            ev.preventDefault();
            cb();
            (_a = this.floatingMenuEl) == null ? void 0 : _a.remove();
            this.floatingMenuEl = null;
          });
        };
        addBtn("\u2795 Insert", async () => {
          await this.appendToAssociatedNote(text, "Extract");
        });
        addBtn("\u{1F4AC} Ask", () => {
          this.textarea.value = `Regarding: "${text.substring(0, 80)}..."

`;
          this.textarea.focus();
          this.textarea.style.height = "auto";
          this.textarea.style.height = this.textarea.scrollHeight + "px";
        });
        addBtn("\u{1F4DD} New Note", async () => {
          await this.appendToAssociatedNote(text, "Extract");
        });
      }, 50);
    });
    this.registerDomEvent(window, "mousedown", (e) => {
      if (this.floatingMenuEl && !this.floatingMenuEl.contains(e.target)) {
        this.floatingMenuEl.remove();
        this.floatingMenuEl = null;
      }
    });
  }
  async appendToAssociatedNote(content, label) {
    var _a;
    let targetFile = null;
    const activeFile = this.app.vault.getAbstractFileByPath(this.currentHistoryPath || "");
    const createFallbackNoteForPdf = activeFile instanceof import_obsidian2.TFile && activeFile.extension === "pdf";
    if (activeFile instanceof import_obsidian2.TFile) {
      if (activeFile.extension === "md") {
        targetFile = activeFile;
      } else if (activeFile.extension === "pdf") {
        const metadataCache = this.app.metadataCache;
        const backlinks = metadataCache.getBacklinksForFile(activeFile);
        if (backlinks && backlinks.data) {
          const paths = Object.keys(backlinks.data);
          if (paths.length > 0) {
            const f = this.app.vault.getAbstractFileByPath(paths[0]);
            if (f instanceof import_obsidian2.TFile)
              targetFile = f;
          }
        }
        if (!targetFile) {
          const mdFiles = this.app.vault.getMarkdownFiles();
          for (const mdFile of mdFiles) {
            const cache = this.app.metadataCache.getFileCache(mdFile);
            const source = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.source;
            if (source === this.currentHistoryPath || source === `[[${activeFile.name}]]` || source === `[[${activeFile.path.replace(/\.[^/.]+$/, "")}]]`) {
              targetFile = mdFile;
              break;
            }
          }
        }
      }
    }
    if (!targetFile) {
      const leaves = this.app.workspace.getLeavesOfType("markdown");
      if (leaves.length > 0)
        targetFile = leaves[0].view.file;
    }
    if (!targetFile && createFallbackNoteForPdf && activeFile instanceof import_obsidian2.TFile) {
      targetFile = await this.createAssociatedNoteForPdf(activeFile, content, label);
      new import_obsidian2.Notice(`Created note for ${activeFile.name}`);
      return;
    }
    if (targetFile) {
      const oldContent = await this.app.vault.read(targetFile);
      const newContent = oldContent + `

--- LLM ${label} ---
` + content + "\n";
      await this.app.vault.modify(targetFile, newContent);
      new import_obsidian2.Notice(`Appended ${label} to ${targetFile.name}`);
    } else {
      new import_obsidian2.Notice("No target note found to append content");
    }
  }
  buildPdfNotePath(pdfFile) {
    const baseName = pdfFile.basename.replace(/[\\/:*?"<>|]/g, "-").trim() || "PDF Note";
    return `inbox/${baseName}.md`;
  }
  async getAvailableRootNotePath(basePath) {
    let candidate = basePath;
    let counter = 2;
    while (await this.app.vault.adapter.exists(candidate)) {
      const baseName = candidate.replace(/\.md$/i, "");
      candidate = `${baseName} ${counter}.md`;
      counter += 1;
    }
    return candidate;
  }
  async createAssociatedNoteForPdf(pdfFile, content, label) {
    const sourceLink = `"[[${pdfFile.path}]]"`;
    const notePath = await this.getAvailableRootNotePath(this.buildPdfNotePath(pdfFile));
    const createdAt = new Date().toISOString();
    const noteContent = `---
source: ${sourceLink}
Date: ${createdAt}
base: "[[Inbox.base]]"
Category:
aliases:
tags:
  - llm-generated
  - pdf-note
---

# ${pdfFile.basename}

--- LLM ${label} ---
${content}
`;
    const note = await this.app.vault.create(notePath, noteContent);
    await this.app.workspace.getLeaf(true).openFile(note);
    return note;
  }
  switchHistory() {
    const activeFile = this.app.workspace.getActiveFile();
    const activePath = activeFile ? activeFile.path : null;
    if (this.currentHistoryPath === activePath)
      return;
    if (this.currentHistoryPath && this.messages.length > 0) {
      this.persistCurrentSession();
      this.saveHistoryToFile();
    }
    if (activePath) {
      this.currentHistoryPath = activePath;
      this.loadActiveSession(activeFile);
    } else {
      this.currentHistoryPath = null;
      this.activeSessionIndex = null;
      this.renderHistory();
      this.renderAttachments();
    }
  }
  showHistoryExplorer() {
    if (!this.currentHistoryPath)
      return;
    const sessions = this.historyCache.get(this.currentHistoryPath) || [];
    const overlay = this.containerEl.createDiv({ cls: "llm-history-overlay" });
    const overlayHeader = overlay.createDiv({ cls: "llm-history-overlay-header" });
    overlayHeader.createDiv({ text: "Conversation History", cls: "llm-history-overlay-title" });
    overlayHeader.createEl("button", { text: "Close", cls: "llm-history-close-btn" }).addEventListener("click", () => overlay.remove());
    const listContainer = overlay.createDiv({ cls: "llm-history-list" });
    sessions.slice().reverse().forEach((s, revIdx) => {
      var _a;
      const actualIdx = sessions.length - 1 - revIdx;
      const item = listContainer.createDiv({ cls: "llm-history-item" });
      const itemCopy = item.createDiv({ cls: "llm-history-item-copy" });
      itemCopy.createDiv({ text: new Date(s.timestamp).toLocaleString(), cls: "llm-history-item-time" });
      itemCopy.createDiv({ text: ((_a = s.messages.find((m) => m.role === "user")) == null ? void 0 : _a.content.substring(0, 64)) || "New Conversation", cls: "llm-history-item-title" });
      const del = item.createEl("button", { text: "Delete", cls: "llm-history-delete-btn" });
      del.addEventListener("click", (ev) => {
        ev.stopPropagation();
        if (confirm("Delete?")) {
          sessions.splice(actualIdx, 1);
          this.historyCache.set(this.currentHistoryPath, sessions);
          this.saveHistoryToFile();
          overlay.remove();
          this.showHistoryExplorer();
        }
      });
      item.addEventListener("click", () => {
        this.activeSessionIndex = actualIdx;
        this.messages = [...s.messages];
        this.attachedFiles = s.attached.map((p) => this.app.vault.getAbstractFileByPath(p)).filter((f) => f instanceof import_obsidian2.TFile);
        this.renderHistory();
        this.renderAttachments();
        overlay.remove();
      });
    });
  }
  renderHistory() {
    this.chatContainer.empty();
    if (!this.messages || this.messages.filter((m) => m.role !== "system").length === 0)
      this.renderWelcomeScreen();
    else
      this.messages.forEach((msg) => {
        if (msg.role !== "system")
          this.addMessage(msg.role, msg.content, true);
      });
  }
  renderAttachments() {
    this.attachmentsDiv.empty();
    this.attachedFiles.forEach((file, index) => {
      const tag = this.attachmentsDiv.createDiv({ cls: "llm-attachment-tag" });
      tag.createSpan({ text: file.name });
      tag.createSpan({ text: "\xD7", cls: "llm-attachment-remove" }).addEventListener("click", () => {
        this.attachedFiles.splice(index, 1);
        this.renderAttachments();
      });
    });
  }
  renderWelcomeScreen() {
    this.chatContainer.empty();
    const welcome = this.chatContainer.createDiv({ cls: "llm-welcome" });
    welcome.createDiv({ text: "AI", cls: "llm-welcome-icon" });
    const textWrapper = welcome.createDiv({ cls: "llm-welcome-text-wrapper" });
    textWrapper.createDiv({ text: "Ready to work with your vault", cls: "llm-welcome-title" });
    textWrapper.createDiv({ text: "Ask about the current note, attach source material, or save useful outputs back into Obsidian.", cls: "llm-welcome-body" });
    const list = textWrapper.createEl("ul", { cls: "llm-welcome-list" });
    list.createEl("li", { text: "Ask questions about your current note or PDF" });
    list.createEl("li", { text: "Select chat text to save or insert into notes" });
    list.createEl("li", { text: "Use shortcuts for quick translations & summaries" });
    list.createEl("li", { text: "Append responses directly to your source content" });
  }
  async handleSend(text, selectedModel = "") {
    this.addMessage("user", text);
    this.setLoading(true);
    const config = this.plugin.settings.models.find((m) => m.name === (selectedModel || this.plugin.settings.model)) || this.plugin.settings.models[0];
    try {
      if (!config)
        throw new Error("No model configured. Please add a model in settings.");
      let contextText = "";
      const files = [...this.attachedFiles];
      const active = this.app.workspace.getActiveFile();
      if (active && !files.find((f) => f.path === active.path))
        files.push(active);
      const isGemini = config.apiUrl.includes("generativelanguage");
      const isAnthropic = config.apiUrl.includes("api.anthropic.com");
      const isOfficialOpenAI = config.apiUrl.includes("api.openai.com");
      const nativeAttachments = [];
      for (const file of files) {
        if (file.extension === "pdf") {
          const buffer = await this.app.vault.readBinary(file);
          if (isGemini || isAnthropic || isOfficialOpenAI) {
            nativeAttachments.push({ name: file.name, mimeType: "application/pdf", data: this.arrayBufferToBase64(buffer) });
          }
          const pdfjs = window.pdfjsLib;
          if (pdfjs) {
            const pdf = await pdfjs.getDocument({ data: new Uint8Array(buffer) }).promise;
            for (let i = 1; i <= Math.min(pdf.numPages, this.maxPdfPages); i++) {
              contextText += (await (await pdf.getPage(i)).getTextContent()).items.map((it) => it.str).join(" ") + "\n";
            }
          }
        } else if (file.extension === "md" || file.extension === "txt")
          contextText += await this.app.vault.read(file) + "\n";
      }
      const apiMsgs = this.buildApiMessages(text, contextText);
      const res = await callLlmApi(
        config.apiUrl,
        config.apiKey,
        selectedModel || this.plugin.settings.model,
        apiMsgs,
        nativeAttachments,
        config.authMode || "api_key"
      );
      this.addMessage("assistant", res);
    } catch (error) {
      this.addMessage("assistant", `**Error:** ${error.message}`);
    } finally {
      this.persistCurrentSession();
      await this.saveHistoryToFile();
      this.setLoading(false);
    }
  }
  buildApiMessages(latestUserText, contextText) {
    const contextBlock = contextText.trim() ? `

Context from attached/current files:
---
${contextText.trim()}
---` : "";
    return [
      { role: "system", content: this.plugin.settings.systemPrompt },
      ...this.messages.map((message, index) => {
        if (message.role === "user" && message.content === latestUserText && index === this.messages.length - 1 && contextBlock) {
          return { ...message, content: `${message.content}${contextBlock}` };
        }
        return { ...message };
      })
    ];
  }
  persistCurrentSession() {
    if (!this.currentHistoryPath)
      return;
    const sessions = this.historyCache.get(this.currentHistoryPath) || [];
    if (this.activeSessionIndex === null) {
      sessions.push({
        timestamp: Date.now(),
        messages: [...this.messages],
        attached: this.attachedFiles.map((f) => f.path)
      });
      this.activeSessionIndex = sessions.length - 1;
    } else if (sessions[this.activeSessionIndex]) {
      sessions[this.activeSessionIndex].messages = [...this.messages];
      sessions[this.activeSessionIndex].attached = this.attachedFiles.map((f) => f.path);
    }
    this.historyCache.set(this.currentHistoryPath, sessions);
  }
  addMessage(role, content, skipPush = false) {
    if (this.chatContainer.querySelector(".llm-welcome"))
      this.chatContainer.empty();
    if (!skipPush)
      this.messages.push({ role, content });
    const wrap = this.chatContainer.createDiv({ cls: `llm-bubble-wrapper ${role}` });
    const bubble = wrap.createDiv({ cls: `llm-bubble ${role}` });
    if (role === "user")
      bubble.innerText = content;
    else {
      import_obsidian2.MarkdownRenderer.render(this.app, content, bubble, "", this);
      const actions = wrap.createDiv({ cls: "llm-bubble-actions" });
      actions.createEl("button", { text: "Copy" }).addEventListener("click", () => {
        navigator.clipboard.writeText(content);
        new import_obsidian2.Notice("Copied to clipboard");
      });
      actions.createEl("button", { text: "Save" }).addEventListener("click", async () => {
        await this.appendToAssociatedNote(content, "Response");
      });
    }
    this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
  }
  setLoading(loading) {
    this.textarea.disabled = loading;
    this.sendButton.disabled = loading;
    if (loading) {
      this.typingBubble = this.chatContainer.createDiv({ cls: "llm-bubble-wrapper assistant" });
      this.typingBubble.createDiv({ cls: "llm-bubble assistant" }).innerHTML = '<div class="llm-typing-indicator"><span>.</span><span>.</span><span>.</span></div>';
    } else if (this.typingBubble) {
      this.typingBubble.remove();
      this.typingBubble = null;
      this.textarea.focus();
    }
  }
  async onClose() {
    var _a;
    (_a = this.floatingMenuEl) == null ? void 0 : _a.remove();
    this.floatingMenuEl = null;
  }
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    const chunkSize = 32768;
    let binary = "";
    for (let i = 0; i < bytes.length; i += chunkSize) {
      const chunk = bytes.subarray(i, i + chunkSize);
      binary += String.fromCharCode(...chunk);
    }
    return window.btoa(binary);
  }
};
var FileSuggestModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    return this.app.vault.getFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  model: "gpt-4o",
  models: [
    { name: "gpt-4o", apiUrl: "https://api.openai.com/v1/chat/completions", apiKey: "", authMode: "api_key" }
  ],
  systemPrompt: "You are a helpful assistant integrated into an Obsidian side panel. You have access to the user's current open document or context in Obsidian. Answer their question based on the context. If they have selected specific text, focus on that text.",
  shortcuts: [
    { label: "Summarize", prompt: "Summarize the document in 3-5 bullet points." },
    { label: "Key Points", prompt: "List the key points." },
    { label: "Translate", prompt: "\u8BF7\u5C06\u6587\u6BB5\u6216\u9009\u4E2D\u5185\u5BB9\u7CBE\u51C6\u7FFB\u8BD1\u6210\u5BB9\u6613\u7406\u89E3\u7684\u4E2D\u6587\u3002" }
  ]
};
var MODEL_PRESETS = [
  { provider: "OpenAI", name: "gpt-4o", apiUrl: "https://api.openai.com/v1/chat/completions", authMode: "api_key" },
  { provider: "OpenAI", name: "gpt-4.1-mini", apiUrl: "https://api.openai.com/v1/chat/completions", authMode: "api_key" },
  { provider: "Codex", name: "gpt-5.4", apiUrl: "https://chatgpt.com/backend-api/codex/responses", authMode: "codex_auth" },
  { provider: "Anthropic", name: "claude-3-5-sonnet-latest", apiUrl: "https://api.anthropic.com/v1/messages", authMode: "api_key" },
  { provider: "Google Gemini", name: "gemini-2.0-flash", apiUrl: "https://generativelanguage.googleapis.com", authMode: "api_key" },
  { provider: "DeepSeek", name: "deepseek-chat", apiUrl: "https://api.deepseek.com/v1/chat/completions", authMode: "api_key" },
  { provider: "OpenRouter", name: "openai/gpt-4o-mini", apiUrl: "https://openrouter.ai/api/v1/chat/completions", authMode: "api_key" },
  { provider: "Groq", name: "llama-3.3-70b-versatile", apiUrl: "https://api.groq.com/openai/v1/chat/completions", authMode: "api_key" },
  { provider: "Moonshot", name: "moonshot-v1-8k", apiUrl: "https://api.moonshot.cn/v1/chat/completions", authMode: "api_key" },
  { provider: "SiliconFlow", name: "Qwen/Qwen2.5-72B-Instruct", apiUrl: "https://api.siliconflow.cn/v1/chat/completions", authMode: "api_key" },
  { provider: "Ollama", name: "llama3.1", apiUrl: "http://localhost:11434/v1/chat/completions", authMode: "api_key" }
];
var LlmPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      CHAT_VIEW_TYPE,
      (leaf) => new ChatView(leaf, this)
    );
    this.addRibbonIcon("bot", "Open LLM Assistant", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-llm-chat-view",
      name: "Open LLM Chat View",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new LlmSettingTab(this.app, this));
  }
  async onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(CHAT_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
      }
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    var _a;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.shortcuts = Array.isArray(this.settings.shortcuts) && this.settings.shortcuts.length > 0 ? this.settings.shortcuts.map((shortcut, index) => {
      var _a2, _b;
      return {
        label: ((_a2 = shortcut == null ? void 0 : shortcut.label) == null ? void 0 : _a2.trim()) || `Shortcut ${index + 1}`,
        prompt: ((_b = shortcut == null ? void 0 : shortcut.prompt) == null ? void 0 : _b.trim()) || ""
      };
    }) : DEFAULT_SETTINGS.shortcuts.map((shortcut) => ({ ...shortcut }));
    if (!this.settings.models || this.settings.models.length === 0) {
      this.settings.models = [];
      if (this.settings.addedModels && this.settings.addedModels.length > 0) {
        this.settings.addedModels.forEach((m) => {
          this.settings.models.push({
            name: m,
            apiUrl: this.settings.apiUrl || "https://api.openai.com/v1/chat/completions",
            apiKey: this.settings.apiKey || "",
            authMode: "api_key"
          });
        });
      } else if (this.settings.model && this.settings.model.includes(",")) {
        const names = this.settings.model.split(",").map((s) => s.trim()).filter(Boolean);
        names.forEach((m) => {
          this.settings.models.push({
            name: m,
            apiUrl: this.settings.apiUrl || "https://api.openai.com/v1/chat/completions",
            apiKey: this.settings.apiKey || "",
            authMode: "api_key"
          });
        });
        this.settings.model = names[0];
      } else if (this.settings.model) {
        this.settings.models.push({
          name: this.settings.model,
          apiUrl: this.settings.apiUrl || "https://api.openai.com/v1/chat/completions",
          apiKey: this.settings.apiKey || "",
          authMode: "api_key"
        });
      } else {
        this.settings.models = [...DEFAULT_SETTINGS.models];
      }
    }
    this.settings.models = this.settings.models.map((model) => {
      var _a2, _b;
      return {
        ...model,
        name: ((_a2 = model.name) == null ? void 0 : _a2.trim()) || "unnamed-model",
        apiUrl: ((_b = model.apiUrl) == null ? void 0 : _b.trim()) || "https://api.openai.com/v1/chat/completions",
        apiKey: model.apiKey || "",
        authMode: model.authMode === "codex_auth" ? "codex_auth" : "api_key"
      };
    });
    if (!this.settings.models.find((model) => model.name === this.settings.model)) {
      this.settings.model = ((_a = this.settings.models[0]) == null ? void 0 : _a.name) || DEFAULT_SETTINGS.model;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var LlmSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.saveTimer = null;
    this.selectedPresetIndex = 0;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "General Preferences" });
    new import_obsidian3.Setting(containerEl).setName("System Prompt").setDesc("Customize the default instructions given to the selected model.").addTextArea((text) => {
      text.inputEl.style.width = "100%";
      text.inputEl.rows = 4;
      text.setValue(this.plugin.settings.systemPrompt || DEFAULT_SETTINGS.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value.trim() || DEFAULT_SETTINGS.systemPrompt;
        this.scheduleSave();
      });
    });
    containerEl.createEl("h2", { text: "LLM for Obsidian Models" });
    new import_obsidian3.Setting(containerEl).setName("Popular Model Presets").setDesc("Quickly add a mainstream provider/model preset, then fine-tune it below if needed.").addDropdown((dropdown) => {
      MODEL_PRESETS.forEach((preset, index) => {
        dropdown.addOption(String(index), `${preset.provider} \xB7 ${preset.name}`);
      });
      dropdown.setValue(String(this.selectedPresetIndex));
      dropdown.onChange((value) => {
        this.selectedPresetIndex = Number(value);
      });
    }).addButton((btn) => btn.setButtonText("Add Preset").setCta().onClick(async () => {
      const preset = MODEL_PRESETS[this.selectedPresetIndex];
      if (!preset) {
        return;
      }
      this.plugin.settings.models.push({
        name: this.getUniqueModelName(preset.name),
        apiUrl: preset.apiUrl,
        apiKey: "",
        authMode: preset.authMode || "api_key"
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    this.plugin.settings.models.forEach((m, index) => {
      const div = containerEl.createDiv({ cls: "model-config-box" });
      div.style.border = "1px solid var(--background-modifier-border)";
      div.style.padding = "10px";
      div.style.marginBottom = "15px";
      div.style.borderRadius = "5px";
      new import_obsidian3.Setting(div).setName(`Model Configuration`).setHeading().addButton((btn) => btn.setButtonText("Remove Model").setWarning().setDisabled(this.plugin.settings.models.length <= 1).onClick(async () => {
        if (this.plugin.settings.models.length <= 1) {
          return;
        }
        this.plugin.settings.models.splice(index, 1);
        if (this.plugin.settings.model === m.name && this.plugin.settings.models.length > 0) {
          this.plugin.settings.model = this.plugin.settings.models[0].name;
        }
        await this.plugin.saveSettings();
        this.display();
      }));
      new import_obsidian3.Setting(div).setName(`Provider / Model Name`).setDesc("e.g. gpt-4o, deepseek-chat").addText((text) => text.setValue(m.name).onChange(async (value) => {
        if (this.plugin.settings.model === m.name) {
          this.plugin.settings.model = value;
        }
        m.name = value;
        this.scheduleSave();
      }));
      new import_obsidian3.Setting(div).setName("Auth Mode").setDesc("Use API key auth for standard providers, or Codex auth to reuse local `codex login` credentials.").addDropdown((dropdown) => {
        dropdown.addOption("api_key", "API Key");
        dropdown.addOption("codex_auth", "Codex Auth");
        dropdown.setValue(m.authMode || "api_key");
        dropdown.onChange(async (value) => {
          m.authMode = value;
          if (value === "codex_auth" && !m.apiUrl.trim()) {
            m.apiUrl = "https://chatgpt.com/backend-api/codex/responses";
          }
          if (value === "codex_auth" && m.apiUrl.includes("/chat/completions")) {
            m.apiUrl = "https://chatgpt.com/backend-api/codex/responses";
          }
          await this.plugin.saveSettings();
          this.display();
        });
      }).addButton((btn) => {
        btn.setButtonText("Test");
        btn.onClick(async () => {
          const modelName = m.name.trim();
          if (!modelName) {
            new import_obsidian3.Notice("Please enter a model name before testing.", 6e3);
            return;
          }
          btn.setDisabled(true);
          btn.setButtonText("Testing...");
          try {
            if (m.authMode === "codex_auth") {
              const authResult = await testCodexAuthState();
              const sourceLabel = authResult.tokenSource === "access_token" ? "access token" : "refresh token";
              const refreshLabel = authResult.lastRefresh ? ` Last refresh: ${new Date(authResult.lastRefresh).toLocaleString()}.` : "";
              new import_obsidian3.Notice(`Codex auth OK. Read ${sourceLabel} from ${authResult.authPath}.${refreshLabel}`, 6e3);
            } else if (!m.apiKey.trim()) {
              new import_obsidian3.Notice("Please enter an API Key before testing this model.", 7e3);
              return;
            }
            const result = await testModelConnection({
              apiUrl: m.apiUrl,
              apiKey: m.apiKey,
              model: modelName,
              authMode: m.authMode || "api_key"
            });
            new import_obsidian3.Notice(`Model test OK for ${modelName}. Response preview: ${result.preview}`, 8e3);
          } catch (error) {
            new import_obsidian3.Notice(`Model test failed for ${modelName}: ${error.message}`, 1e4);
          } finally {
            btn.setButtonText("Test");
            btn.setDisabled(false);
          }
        });
      });
      new import_obsidian3.Setting(div).setName(`API URL`).setDesc(m.authMode === "codex_auth" ? "Codex auth usually uses https://chatgpt.com/backend-api/codex/responses" : "").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(m.apiUrl).onChange(async (value) => {
        m.apiUrl = value;
        this.scheduleSave();
      }));
      new import_obsidian3.Setting(div).setName(`API Key`).setDesc(m.authMode === "codex_auth" ? "Not needed in Codex auth mode. The plugin will read ~/.codex/auth.json from your local codex login." : "").addText((text) => {
        text.inputEl.type = "password";
        text.setDisabled(m.authMode === "codex_auth");
        text.setValue(m.apiKey).onChange(async (value) => {
          m.apiKey = value;
          this.scheduleSave();
        });
      });
    });
    new import_obsidian3.Setting(containerEl).addButton((btn) => btn.setButtonText("Add Another Model").setCta().onClick(async () => {
      this.plugin.settings.models.push({
        name: "new-model",
        apiUrl: "https://api.openai.com/v1/chat/completions",
        apiKey: "",
        authMode: "api_key"
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h2", { text: "Quick Prompts" });
    containerEl.createEl("p", {
      text: "Manage the shortcut buttons shown above the chat input.",
      cls: "setting-item-description"
    });
    this.plugin.settings.shortcuts.forEach((shortcut, index) => {
      const div = containerEl.createDiv({ cls: "model-config-box" });
      div.style.border = "1px solid var(--background-modifier-border)";
      div.style.padding = "10px";
      div.style.marginBottom = "15px";
      div.style.borderRadius = "5px";
      new import_obsidian3.Setting(div).setName(`Quick Prompt ${index + 1}`).setHeading();
      new import_obsidian3.Setting(div).setName("Button Label").setDesc("Short text shown on the shortcut button.").addText((text) => text.setValue(shortcut.label).onChange((value) => {
        shortcut.label = value.trim() || `Shortcut ${index + 1}`;
        this.scheduleSave();
      }));
      new import_obsidian3.Setting(div).setName("Prompt").setDesc("Message sent when the shortcut is clicked.").addTextArea((text) => {
        text.inputEl.style.width = "100%";
        text.inputEl.rows = 3;
        text.setValue(shortcut.prompt).onChange((value) => {
          shortcut.prompt = value.trim();
          this.scheduleSave();
        });
      }).addButton((btn) => btn.setButtonText("Remove Prompt").setWarning().onClick(async () => {
        this.plugin.settings.shortcuts.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
    });
    new import_obsidian3.Setting(containerEl).addButton((btn) => btn.setButtonText("Add Quick Prompt").setCta().onClick(async () => {
      this.plugin.settings.shortcuts.push({
        label: "New Prompt",
        prompt: "Write your prompt here."
      });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
  scheduleSave() {
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
    }
    this.saveTimer = window.setTimeout(() => {
      this.plugin.saveSettings();
      this.saveTimer = null;
    }, 250);
  }
  getUniqueModelName(baseName) {
    const existingNames = new Set(this.plugin.settings.models.map((model) => model.name));
    if (!existingNames.has(baseName)) {
      return baseName;
    }
    let suffix = 2;
    while (existingNames.has(`${baseName} (${suffix})`)) {
      suffix += 1;
    }
    return `${baseName} (${suffix})`;
  }
};
